defaults:
  - mlflow: mlflow_local
  - data: catdog_data
  - model: fcnn
  - img_transforms: config_transforms
  - _self_
infer:
  batch_size: 256
  ckpt_path: ${hydra:runtime.cwd}/models
  ckpt_name: model_fcnn
